package com.example.subfeature.pakar.fragments.nine

import androidx.lifecycle.*
import com.example.core_data.api.ApiEvent
import com.example.core_data.domain.Answer
import com.example.core_data.domain.Answers
import com.example.core_data.domain.User
import com.example.core_data.repository.AnswerRepository
import com.example.core_data.repository.AuthRepository
import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.launch


class PakarNinethViewModel(
    val authRepository: AuthRepository,
    val answerRepository: AnswerRepository
) : ViewModel() {

    val auth: LiveData<User?> = liveData {
        emit(authRepository.getAuth())
    }

    private val formDataQuestions = HashMap<String, String>()
    fun putFormDataValue(
        id: String,
        value: String = "0"
    ) {
        formDataQuestions.clear()
        formDataQuestions[id] = value
    }

    fun getFinalData(): Answers {
        val listAnswer = arrayListOf<Answer>()
        val data = formDataQuestions.filter { it.value != "0" }
        data.forEach {
            listAnswer.add(Answer(answer = it.key))
        }
        return listAnswer
    }


    private val _isDataSaved = MutableLiveData<Boolean>()
    val isDataSaved: LiveData<Boolean> = _isDataSaved

    private val _result = MutableLiveData<String>()
    val result: LiveData<String> = _result

    var siswaId: Long = 0L

    fun saveQuestionAnswer(
        siswaId: Long,
        answers: Answers
    ){
        viewModelScope.launch {
            answerRepository.saveAnswer(siswaId, findAnswer(answers),  answers)
                .collect {
                    _isDataSaved.value = it is ApiEvent.OnSuccess<*>
                    _result.value = findAnswer(answers)
                }
        }
    }

    private fun findAnswer(answers: Answers) : String {

        return when {

            //region IPA

            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M03" && answers[6].answer =="M05" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M03" && answers[6].answer =="M06" && answers[7].answer =="M07" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" ->"IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M03" && answers[6].answer =="M06" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M03" && answers[6].answer =="M07" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M03" && answers[6].answer =="M05" && answers[7].answer =="M06" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M03" && answers[6].answer =="M05" && answers[7].answer =="M07" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M03" && answers[6].answer =="M05" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M03" && answers[6].answer =="M06" && answers[7].answer =="M07" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"

            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M04" && answers[6].answer =="M06" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M04" && answers[6].answer =="M07" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M04" && answers[6].answer =="M07" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M02" && answers[4].answer =="M03" && answers[5].answer =="M04" && answers[6].answer =="M05" && answers[7].answer =="M06" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M02" && answers[4].answer =="M03" && answers[5].answer =="M04" && answers[6].answer =="M05" && answers[7].answer =="M07" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M02" && answers[4].answer =="M03" && answers[5].answer =="M04" && answers[6].answer =="M05" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M02" && answers[4].answer =="M03" && answers[5].answer =="M04" && answers[6].answer =="M06" && answers[7].answer =="M07" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M02" && answers[4].answer =="M03" && answers[5].answer =="M04" && answers[6].answer =="M06" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M02" && answers[4].answer =="M03" && answers[5].answer =="M04" && answers[6].answer =="M07" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M03" && answers[4].answer =="M04" && answers[5].answer =="M01" && answers[6].answer =="M05" && answers[7].answer =="M06" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"

            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M03" && answers[4].answer =="M04" && answers[5].answer =="M01" && answers[6].answer =="M05" && answers[7].answer =="M07" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M03" && answers[4].answer =="M04" && answers[5].answer =="M01" && answers[6].answer =="M05" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M03" && answers[4].answer =="M04" && answers[5].answer =="M01" && answers[6].answer =="M06" && answers[7].answer =="M07" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M03" && answers[4].answer =="M04" && answers[5].answer =="M01" && answers[6].answer =="M06" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M03" && answers[4].answer =="M04" && answers[5].answer =="M01" && answers[6].answer =="M07" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M03" && answers[6].answer =="M05" && answers[7].answer =="M06" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M03" && answers[6].answer =="M05" && answers[7].answer =="M07" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M03" && answers[6].answer =="M05" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M03" && answers[6].answer =="M06" && answers[7].answer =="M07" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M03" && answers[6].answer =="M06" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"

            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M03" && answers[6].answer =="M07" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M04" && answers[6].answer =="M05" && answers[7].answer =="M06" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M04" && answers[6].answer =="M05" && answers[7].answer =="M07" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M04" && answers[6].answer =="M05" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M04" && answers[6].answer =="M06" && answers[7].answer =="M07" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M04" && answers[6].answer =="M06" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M04" && answers[6].answer =="M07" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M02" && answers[4].answer =="M03" && answers[5].answer =="M04" && answers[6].answer =="M05" && answers[7].answer =="M06" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M02" && answers[4].answer =="M03" && answers[5].answer =="M04" && answers[6].answer =="M05" && answers[7].answer =="M07" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M02" && answers[4].answer =="M03" && answers[5].answer =="M04" && answers[6].answer =="M05" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"

            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M02" && answers[4].answer =="M03" && answers[5].answer =="M04" && answers[6].answer =="M06" && answers[7].answer =="M07" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M02" && answers[4].answer =="M03" && answers[5].answer =="M04" && answers[6].answer =="M06" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M02" && answers[4].answer =="M03" && answers[5].answer =="M04" && answers[6].answer =="M07" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M03" && answers[4].answer =="M04" && answers[5].answer =="M01" && answers[6].answer =="M05" && answers[7].answer =="M06" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M03" && answers[4].answer =="M04" && answers[5].answer =="M01" && answers[6].answer =="M05" && answers[7].answer =="M07" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M03" && answers[4].answer =="M04" && answers[5].answer =="M01" && answers[6].answer =="M05" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M03" && answers[4].answer =="M04" && answers[5].answer =="M01" && answers[6].answer =="M06" && answers[7].answer =="M07" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M03" && answers[4].answer =="M04" && answers[5].answer =="M01" && answers[6].answer =="M06" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M03" && answers[4].answer =="M04" && answers[5].answer =="M01" && answers[6].answer =="M07" && answers[7].answer =="M08" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer =="M01" && answers[4].answer =="M02" && answers[5].answer =="M03" && answers[6].answer =="M05" && answers[7].answer =="M06" && answers[8].answer =="P01" && answers[9].answer =="N01" && answers[10].answer =="C01" && answers[11].answer =="D01" -> "IPA"

            //endregion
            //region IPS

            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M05" && answers[7].answer =="M06" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M05" && answers[7].answer =="M07" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M05" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M06" && answers[7].answer =="M07" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M06" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M07" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M04" && answers[6].answer =="M05" && answers[7].answer =="M06" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M04" && answers[6].answer =="M05" && answers[7].answer =="M07" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M04" && answers[6].answer =="M05" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M04" && answers[6].answer =="M06" && answers[7].answer =="M07" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"

            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M04" && answers[6].answer =="M06" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M04" && answers[6].answer =="M07" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M02" && answers[4].answer == "M03" && answers[5].answer =="M04" && answers[6].answer =="M05" && answers[7].answer =="M06" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M02" && answers[4].answer == "M03" && answers[5].answer =="M04" && answers[6].answer =="M05" && answers[7].answer =="M07" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M02" && answers[4].answer == "M03" && answers[5].answer =="M04" && answers[6].answer =="M05" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M02" && answers[4].answer == "M03" && answers[5].answer =="M04" && answers[6].answer =="M06" && answers[7].answer =="M07" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M02" && answers[4].answer == "M03" && answers[5].answer =="M04" && answers[6].answer =="M06" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M02" && answers[4].answer == "M03" && answers[5].answer =="M04" && answers[6].answer =="M07" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M03" && answers[4].answer == "M04" && answers[5].answer =="M01" && answers[6].answer =="M05" && answers[7].answer =="M06" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M03" && answers[4].answer == "M04" && answers[5].answer =="M01" && answers[6].answer =="M05" && answers[7].answer =="M07" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"

            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M03" && answers[4].answer == "M04" && answers[5].answer =="M01" && answers[6].answer =="M05" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M03" && answers[4].answer == "M04" && answers[5].answer =="M01" && answers[6].answer =="M06" && answers[7].answer =="M07" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M03" && answers[4].answer == "M04" && answers[5].answer =="M01" && answers[6].answer =="M06" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M03" && answers[4].answer == "M04" && answers[5].answer =="M01" && answers[6].answer =="M07" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPS"

            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M05" && answers[7].answer =="M06" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M05" && answers[7].answer =="M07" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M05" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M06" && answers[7].answer =="M07" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M06" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPA"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M07" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPA"

            //endregion
            //region IPC

            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M05" && answers[7].answer =="M06" && answers[8].answer =="P02" && answers[9].answer =="N09" && answers[10].answer =="C02" && answers[11].answer =="D02" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M05" && answers[7].answer =="M07" && answers[8].answer =="P02" && answers[9].answer =="N09" && answers[10].answer =="C02" && answers[11].answer =="D02" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M05" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N09" && answers[10].answer =="C02" && answers[11].answer =="D02" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M06" && answers[7].answer =="M07" && answers[8].answer =="P02" && answers[9].answer =="N09" && answers[10].answer =="C02" && answers[11].answer =="D02" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M06" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N09" && answers[10].answer =="C02" && answers[11].answer =="D02" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M07" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N09" && answers[10].answer =="C02" && answers[11].answer =="D02" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M04" && answers[6].answer =="M05" && answers[7].answer =="M06" && answers[8].answer =="P02" && answers[9].answer =="N09" && answers[10].answer =="C02" && answers[11].answer =="D02" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M04" && answers[6].answer =="M05" && answers[7].answer =="M07" && answers[8].answer =="P02" && answers[9].answer =="N09" && answers[10].answer =="C02" && answers[11].answer =="D02" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M04" && answers[6].answer =="M05" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N09" && answers[10].answer =="C02" && answers[11].answer =="D02" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M04" && answers[6].answer =="M06" && answers[7].answer =="M07" && answers[8].answer =="P02" && answers[9].answer =="N09" && answers[10].answer =="C02" && answers[11].answer =="D02" -> "IPC"

            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M04" && answers[6].answer =="M06" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N09" && answers[10].answer =="C02" && answers[11].answer =="D02" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M04" && answers[6].answer =="M07" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N09" && answers[10].answer =="C02" && answers[11].answer =="D02" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M02" && answers[4].answer == "M03" && answers[5].answer =="M04" && answers[6].answer =="M05" && answers[7].answer =="M06" && answers[8].answer =="P02" && answers[9].answer =="N09" && answers[10].answer =="C02" && answers[11].answer =="D02" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M02" && answers[4].answer == "M03" && answers[5].answer =="M04" && answers[6].answer =="M05" && answers[7].answer =="M07" && answers[8].answer =="P02" && answers[9].answer =="N09" && answers[10].answer =="C02" && answers[11].answer =="D02" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M02" && answers[4].answer == "M03" && answers[5].answer =="M04" && answers[6].answer =="M05" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N09" && answers[10].answer =="C02" && answers[11].answer =="D02" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M02" && answers[4].answer == "M03" && answers[5].answer =="M04" && answers[6].answer =="M06" && answers[7].answer =="M07" && answers[8].answer =="P02" && answers[9].answer =="N09" && answers[10].answer =="C02" && answers[11].answer =="D02" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M02" && answers[4].answer == "M03" && answers[5].answer =="M04" && answers[6].answer =="M06" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N09" && answers[10].answer =="C02" && answers[11].answer =="D02" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M02" && answers[4].answer == "M03" && answers[5].answer =="M04" && answers[6].answer =="M07" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N09" && answers[10].answer =="C02" && answers[11].answer =="D02" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M03" && answers[4].answer == "M04" && answers[5].answer =="M01" && answers[6].answer =="M05" && answers[7].answer =="M06" && answers[8].answer =="P02" && answers[9].answer =="N09" && answers[10].answer =="C02" && answers[11].answer =="D02" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B05" && answers[3].answer == "M03" && answers[4].answer == "M04" && answers[5].answer =="M01" && answers[6].answer =="M05" && answers[7].answer =="M07" && answers[8].answer =="P02" && answers[9].answer =="N09" && answers[10].answer =="C02" && answers[11].answer =="D02" -> "IPC"

            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M05" && answers[7].answer =="M06" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M05" && answers[7].answer =="M07" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M05" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M06" && answers[7].answer =="M07" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M06" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M07" && answers[7].answer =="M08" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M05" && answers[7].answer =="M06" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPC"
            answers[0].answer =="J01" && answers[1].answer=="B01" && answers[2].answer=="B02" && answers[3].answer == "M01" && answers[4].answer == "M02" && answers[5].answer =="M03" && answers[6].answer =="M05" && answers[7].answer =="M07" && answers[8].answer =="P02" && answers[9].answer =="N01" && answers[10].answer =="C02" && answers[11].answer =="D01" -> "IPC"

            //endregion IPC
            else -> {
                ""
            }
        }
    }

}